spring.application.name=complianceautomationplatform
spring.datasource.url=jdbc:postgresql://localhost:5432/compliance_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=thisisasecretkeyforjwttokendontshareanyonwithanyone
jwt.expiration=86400000
server.port=8080